export const AUTHENTICATION_SUCCEEDED = 'AUTHENTICATION_SUCCEEDED'
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED'
export const JWT_REVOKED_SUCCEEDED = 'JWT_REVOKED_SUCCEEDED'
export const JWT_REVOKED_FAILED = 'JWT_REVOKED_FAILED'